{
  "hash": "57ef1faa61a22ad2bc47884719663f80",
  "result": {
    "engine": "jupyter",
    "markdown": "# The pipeline\n\nA walkthrough of every stage between `metadata.csv` and a reported score, with the reasoning for each decision.\n\nThis notebook **does not train anything**. It runs in seconds and needs no image files: the data stages work from the metadata alone, and the model stages are demonstrated on small synthetic inputs. Training is `ham10000 train configs/<name>.yaml`; results are in `02_results.ipynb`.\n\nThe stages:\n\n```\nmetadata.csv\n   -> load and validate\n   -> label scheme          (which classes, and how they are grouped)\n   -> lesion-level split    (the leakage control)\n   -> balancing             (training set only)\n   -> validation expansion  (test-time augmentation)\n   -> transform\n   -> model                 (architecture and freezing)\n   -> training\n   -> inference             (per-image probabilities)\n   -> aggregation           (per-image -> per-lesion)\n   -> decision rule         (sensitivity bias)\n   -> evaluation\n```\n\n## 1. Load and validate\n\n::: {#2 .cell execution_count=1}\n``` {.python .cell-code}\nfrom ham10000.config import Settings\nfrom ham10000.data import load_metadata\n\nsettings = Settings.resolve()\nmetadata = load_metadata(settings.metadata_csv)\n\nprint(f\"{len(metadata):,} images, {metadata['lesion_id'].nunique():,} lesions\")\nmetadata.head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n10,015 images, 7,470 lesions\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>lesion_id</th>\n      <th>num_images</th>\n      <th>image_id</th>\n      <th>dx</th>\n      <th>dx_type</th>\n      <th>age</th>\n      <th>sex</th>\n      <th>localization</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>HAM_0000118</td>\n      <td>2</td>\n      <td>ISIC_0027419</td>\n      <td>bkl</td>\n      <td>histo</td>\n      <td>80.0</td>\n      <td>male</td>\n      <td>scalp</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>HAM_0000118</td>\n      <td>2</td>\n      <td>ISIC_0025030</td>\n      <td>bkl</td>\n      <td>histo</td>\n      <td>80.0</td>\n      <td>male</td>\n      <td>scalp</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>HAM_0002730</td>\n      <td>2</td>\n      <td>ISIC_0026769</td>\n      <td>bkl</td>\n      <td>histo</td>\n      <td>80.0</td>\n      <td>male</td>\n      <td>scalp</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n`load_metadata` adds a `num_images` column and refuses a file with duplicate `image_id` values. That check matters: nothing downstream would fail loudly on a repeated identifier, but the split would silently designate the same image for a lesion twice.\n\n## 2. Label scheme\n\nThe seven diagnoses can be modelled individually, or grouped. `LabelScheme` turns a specification into the two mappings the pipeline needs: diagnosis to integer, and integer to class name.\n\n::: {#tbl-schemes .cell tbl-cap='Where melanoma lands under four class schemes.' execution_count=2}\n``` {.python .cell-code}\nfrom ham10000.data import LabelScheme\n\npresent = set(metadata[\"dx\"].unique())\n\nseven = LabelScheme.build([\"mel\", \"nv\", \"bkl\", \"bcc\", \"akiec\", \"vasc\", \"df\"], present)\nbinary = LabelScheme.build(\n    {\"malignant\": [\"mel\", \"bcc\", \"akiec\"], \"benign\": [\"nv\", \"bkl\", \"df\", \"vasc\"]},\n    present,\n)\n# Naming two diagnoses does not by itself give a two-class problem: the other\n# five are still in the data and have to go somewhere.\nmel_nv = LabelScheme.build([\"mel\", \"nv\"], present)\n# Restricting the data first is what makes it genuinely binary. This is what\n# `restrict: {dx: [mel, nv]}` does in the demo configuration.\nrestricted = LabelScheme.build([\"mel\", \"nv\"], {\"mel\", \"nv\"})\n\nprint(\"seven-class     :\", seven.codes)\nprint(\"malignant/benign:\", binary.codes)\nprint(\"mel and nv named:\", mel_nv.codes)\nprint(\"data restricted :\", restricted.codes)\nimport pandas as pd\n\npd.DataFrame(\n    {\n        name: {\n            \"melanoma index\": scheme.mapping[\"mel\"],\n            \"called\": scheme.codes[scheme.mapping[\"mel\"]],\n            \"classes\": scheme.n_classes,\n            \"chance\": round(1 / scheme.n_classes, 3),\n        }\n        for name, scheme in {\n            \"seven-class\": seven,\n            \"malignant/benign\": binary,\n            \"mel and nv named\": mel_nv,\n            \"data restricted\": restricted,\n        }.items()\n    }\n).T\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nseven-class     : {0: 'akiec', 1: 'bcc', 2: 'bkl', 3: 'df', 4: 'mel', 5: 'nv', 6: 'vasc'}\nmalignant/benign: {0: 'benign', 1: 'malignant'}\nmel and nv named: {0: 'other', 1: 'mel', 2: 'nv'}\ndata restricted : {0: 'mel', 1: 'nv'}\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>melanoma index</th>\n      <th>called</th>\n      <th>classes</th>\n      <th>chance</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>seven-class</th>\n      <td>4</td>\n      <td>mel</td>\n      <td>7</td>\n      <td>0.143</td>\n    </tr>\n    <tr>\n      <th>malignant/benign</th>\n      <td>1</td>\n      <td>malignant</td>\n      <td>2</td>\n      <td>0.5</td>\n    </tr>\n    <tr>\n      <th>mel and nv named</th>\n      <td>1</td>\n      <td>mel</td>\n      <td>3</td>\n      <td>0.333</td>\n    </tr>\n    <tr>\n      <th>data restricted</th>\n      <td>0</td>\n      <td>mel</td>\n      <td>2</td>\n      <td>0.5</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nNaming `mel` and `nv` gives three classes, not two (@tbl-schemes). The other five diagnoses are still in the data, so they collect in other, and the model has a third answer available. Restricting the data first is what makes the problem genuinely binary, which is why the demo configuration sets restrict: `{dx: [mel, nv]}` before naming its classes.\n\nNote that melanoma has a different integer under every scheme. That is not an inconsistency to be fixed, it is what an integer label means: a position in a particular scheme, assigned by sorting the class names, with other pinned to index 0 when it exists. A stored probability table has a column per class in that order, and a trained model has one output per class in that order, so a checkpoint and a scheme only make sense together. Scoring a seven-class checkpoint under a binary scheme would silently read the first two of seven outputs and produce entirely plausible nonsense, which is why `predict_probabilities` refuses when the widths disagree.\n\nTwo conventions are load-bearing, because stored artefacts depend on them.\n\n1. **Class names are sorted before indices are assigned**, so the same specification always yields the same integer for the same class. Without that, a model trained in one session is silently mismatched with predictions decoded in another.\n\n2. **A specification that does not cover every diagnosis gains an `other` class at index 0**, shifting the rest up. Groups must also be disjoint: a diagnosis appearing in two of them is rejected rather than quietly assigned to whichever was declared last.\n\n::: {#8 .cell execution_count=3}\n``` {.python .cell-code}\npartial = LabelScheme.build({\"mel\": [\"mel\"], \"nv\": [\"nv\"]}, present)\nprint(\"partial specification:\", partial.codes)\nprint(\"bkl falls into       :\", partial.codes[partial.mapping[\"bkl\"]])\nprint(\"probability columns  :\", partial.probability_columns)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npartial specification: {0: 'other', 1: 'mel', 2: 'nv'}\nbkl falls into       : other\nprobability columns  : ['prob_other', 'prob_mel', 'prob_nv']\n```\n:::\n:::\n\n\n## 3. The lesion-level split\n\nThe most consequential decision in the project. 1,956 lesions are photographed more than once, and those images are near-duplicates. Splitting at the image level would place near-identical photographs of one lesion on both sides of the boundary, so the validation score would measure memorisation rather than generalisation.\n\n::: {#10 .cell execution_count=4}\n``` {.python .cell-code}\nfrom ham10000.data import SplitConfig, assign_splits, lesion_overlap\n\nmetadata[\"label\"] = metadata[\"dx\"].map(seven.mapping)\n\nsplit = SplitConfig(train_val_ratio=3, seed=0, keep_first=False, stratified=True)\nassignment = assign_splits(metadata, split)\nannotated = metadata.assign(set=assignment.sets)\n\nprint(f\"train lesions {len(assignment.train_lesions):,}\")\nprint(f\"val lesions   {len(assignment.val_lesions):,}\")\nprint(annotated[\"set\"].value_counts().sort_index().to_string())\nprint(\"\\nlesions on both sides:\", lesion_overlap(annotated) or \"none\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntrain lesions 5,600\nval lesions   1,870\nset\nt1    5600\nta    1878\nv1    1870\nva     667\n\nlesions on both sides: none\n```\n:::\n:::\n\n\nThe `set` column encodes two experiments at once:\n\n| value | meaning |\n|---|---|\n| `t1` | training, and the one designated image for its lesion |\n| `ta` | training, an additional image of a lesion already represented |\n| `v1` | validation, designated image |\n| `va` | validation, additional image |\n\nOne image per lesion uses `t1`/`v1`; all images uses `t1 | ta` and `v1 | va`. Since `ta` is defined as the images of training lesions *excluding* `t1`, the union is exactly the images of the training lesions, with no double counting.\n\n`stratified=True` applies the ratio within each class. With dermatofibroma at 73 lesions, an unstratified split can leave a rare class badly represented on one side by chance.\n\n::: {#12 .cell execution_count=5}\n``` {.python .cell-code}\n# Both images of a multi-image lesion land on the same side, always.\nmulti = annotated[annotated[\"num_images\"] > 1]\nsides = multi.assign(side=multi[\"set\"].str[0])\nprint(\"lesions whose images span both sides:\",\n      int((sides.groupby(\"lesion_id\")[\"side\"].nunique() > 1).sum()))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlesions whose images span both sides: 0\n```\n:::\n:::\n\n\n## 4. Balancing\n\nNevi are 72% of lesions. A classifier answering \"nevus\" unconditionally scores about 0.72 plain accuracy while being useless, and cross-entropy rewards it for doing so. Resampling toward uniform class counts removes the incentive.\n\nResampling is lesion-aware, not row-level. To draw `N` images of a class over its `D` lesions, write `N = Q·D + R`: every lesion contributes `Q` images and `R` randomly chosen lesions contribute one more. Within a lesion holding `k` images, `Q = q·k + r`: each image taken `q` times, `r` of them once more.\n\nSampling is therefore as uniform as integer arithmetic allows at both levels. A lesion photographed five times does not get five times the influence of one photographed once, which is the concern that motivates the split, applied here to resampling.\n\n::: {#tbl-balance .cell tbl-cap='Resampling factors by class, for a target of 1,000 each.' execution_count=6}\n``` {.python .cell-code}\nfrom ham10000.data import balance\n\ntrain = annotated[annotated[\"set\"].isin([\"t1\", \"ta\"])].copy()\ntargets = {dx: 1000 for dx in train[\"dx\"].unique()}\nbalanced = balance(train, targets, seed=0, one_image_per_lesion=False)\n\nimport pandas as pd\n\ncomparison = pd.DataFrame({\"before\": train[\"dx\"].value_counts(),\n                           \"after\": balanced[\"dx\"].value_counts()})\ncomparison[\"factor\"] = (comparison[\"after\"] / comparison[\"before\"]).round(1)\ncomparison[\"lesions\"] = train.groupby(\"dx\")[\"lesion_id\"].nunique()\ncomparison.sort_values(\"factor\")\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>before</th>\n      <th>after</th>\n      <th>factor</th>\n      <th>lesions</th>\n    </tr>\n    <tr>\n      <th>dx</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>nv</th>\n      <td>5007</td>\n      <td>1000</td>\n      <td>0.2</td>\n      <td>4052</td>\n    </tr>\n    <tr>\n      <th>bkl</th>\n      <td>823</td>\n      <td>1000</td>\n      <td>1.2</td>\n      <td>545</td>\n    </tr>\n    <tr>\n      <th>mel</th>\n      <td>827</td>\n      <td>1000</td>\n      <td>1.2</td>\n      <td>460</td>\n    </tr>\n    <tr>\n      <th>bcc</th>\n      <td>388</td>\n      <td>1000</td>\n      <td>2.6</td>\n      <td>245</td>\n    </tr>\n    <tr>\n      <th>akiec</th>\n      <td>244</td>\n      <td>1000</td>\n      <td>4.1</td>\n      <td>171</td>\n    </tr>\n    <tr>\n      <th>vasc</th>\n      <td>107</td>\n      <td>1000</td>\n      <td>9.3</td>\n      <td>73</td>\n    </tr>\n    <tr>\n      <th>df</th>\n      <td>82</td>\n      <td>1000</td>\n      <td>12.2</td>\n      <td>54</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nNote what the `factor` column exposes (@tbl-balance). Nevi are cut to a fifth; dermatofibroma is repeated twelve times over 54 distinct lesions. Random cropping means those repeats are different views rather than identical copies, but the underlying lesion count does not change, and a recall figure for `df` says more about those 54 lesions than about the class.\n\nThe same arithmetic handles both directions: when `N < D`, `Q = 0`, so no lesion contributes a base image and exactly `N` lesions contribute one each. That is the undersampling path, and it draws from distinct lesions rather than dropping rows arbitrarily.\n\n**Balancing is applied to training data only.** `balance` refuses a frame containing validation rows, because repeating a validation lesion would count its errors twice and inflate the reported score.\n\n::: {#16 .cell execution_count=7}\n``` {.python .cell-code}\ntry:\n    balance(annotated, targets)\nexcept ValueError as error:\n    print(error)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFrame contains 2537 validation row(s). Balancing must be applied to training data only, or validation performance is inflated by repeated lesions.\n```\n:::\n:::\n\n\n## 5. Validation expansion\n\nEach validation lesion is scored several times under the evaluation transform and the predictions are combined into a single verdict. This is test-time augmentation, and it only makes sense because the transform is stochastic: with a deterministic transform it would produce identical predictions and cost runtime for nothing. Every lesion is repeated the same number of times, so the expansion cannot reweight the validation set across classes.\n\nWhether this helps is measured in section 9, once there is a run to measure it on.\n\n::: {#18 .cell execution_count=8}\n``` {.python .cell-code}\nfrom ham10000.data import expand_validation\n\nvalidation = annotated[annotated[\"set\"].isin([\"v1\", \"va\"])].copy()\nexpanded = expand_validation(validation, 3, seed=0)\n\nprint(f\"{len(validation):,} images -> {len(expanded):,} after 3x expansion\")\nprint(\"repeats per lesion:\", sorted(int(v) for v in expanded[\"lesion_id\"].value_counts().unique()))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n2,537 images -> 5,610 after 3x expansion\nrepeats per lesion: [3]\n```\n:::\n:::\n\n\n## 6. Transform\n\nDeclared in the config rather than in code, so an experiment's augmentation is part of its identity.\n\n::: {#20 .cell execution_count=9}\n``` {.python .cell-code}\nfrom ham10000.experiment import build_transform, load_config\n\nconfig = load_config(settings.root / \"configs\" / \"04_balanced_random_crop.yaml\")\ntransform = build_transform(config.transform)\ntransform\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\nCompose(\n    RandomCrop(size=(300, 300), padding=None)\n    Resize(size=[224, 224], interpolation=bilinear, max_size=None, antialias=True)\n    ToTensor()\n    Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n)\n```\n:::\n:::\n\n\n`RandomCrop(300)` then `Resize(224)` takes a random 300x300 window of the 600x450 image and scales it to the network's input size. That is a meaningful augmentation for this domain: a dermatoscopic image has no canonical framing, so the lesion's position and scale within the frame carry no diagnostic information and a model should not depend on them.\n\n`Normalize` uses ImageNet channel statistics, matching the distribution the pretrained weights expect.\n\nNote that this same transform is applied at validation time, which is what makes the expansion above work.\n\n## 7. Model and freezing\n\nTransfer learning: take an ImageNet-pretrained backbone, replace its head with one sized to the task, and train some suffix of the network.\n\n::: {#23 .cell execution_count=10}\n``` {.python .cell-code}\nfrom ham10000.models import FreezeStrategy, apply_freezing, build_classifier\n\nmodel = build_classifier(\n    \"resnet18\", n_classes=seven.n_classes, strategy=\"last_block\", pretrained=False\n)\n\ntotal = sum(p.numel() for p in model.parameters())\nfor strategy in FreezeStrategy:\n    apply_freezing(model, strategy)\n    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)\n    print(f\"{strategy.value:11s} {trainable:>11,} / {total:,} trainable \"\n          f\"({trainable / total:.2%})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nall          11,180,103 / 11,180,103 trainable (100.00%)\nlast_block    8,397,319 / 11,180,103 trainable (75.11%)\nhead_only         3,591 / 11,180,103 trainable (0.03%)\n```\n:::\n:::\n\n\nEarly layers hold generic edge and texture filters that transfer well from ImageNet; late layers hold class-specific structure worth re-learning. Freezing the early ones is faster and reduces overfitting on a dataset this size. `head_only` is a genuine baseline rather than merely a cheap one: it measures how much of the task ImageNet features already solve, with no fine-tuning at all.\n\n## 8. Training\n\n`train_model` is a loop over epochs: forward, loss, backward, step; then a validation pass. Loss is cross-entropy, the optimiser is Adam at 1e-4, a conservative rate appropriate to fine-tuning, since a larger one can destroy pretrained features in the first few steps.\n\nOnly the trainable parameters go to the optimiser. Handing frozen tensors to Adam would allocate optimiser state that never updates, and for optimisers with weight decay can perturb weights that were meant to stay fixed.\n\nThe final epoch is saved rather than the best. With no early stopping, a run that begins overfitting at epoch 5 still ships epoch 10, which is a real weakness and visible in the loss curves in `02_results.ipynb`. Setting `save_best` keeps the lowest-validation-loss epoch instead, with a caveat: choosing an epoch by validation loss and then reporting validation metrics is selection on the evaluation set, so the reported score is optimistic by an unknown amount. Note also that the selection criterion and the reported metric are different quantities, so the lowest-loss epoch is not necessarily the most accurate one.\n\n::: {#26 .cell execution_count=11}\n``` {.python .cell-code}\nprint(f\"epochs        {config.training.epochs}\")\nprint(f\"batch size    {config.training.batch_size}\")\nprint(f\"learning rate {config.training.learning_rate}\")\nprint(f\"save best     {config.training.save_best}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nepochs        10\nbatch size    32\nlearning rate 0.0001\nsave best     False\n```\n:::\n:::\n\n\n## 9. Inference and aggregation\n\nThe model scores each image independently. Something has to reconcile several images of one lesion into a single answer, because a lesion is what a clinician decides about. There are two places to do it, and they are not equivalent.\n\n::: {#28 .cell execution_count=12}\n``` {.python .cell-code}\nimport pandas as pd\n\n# A small synthetic probability table: one lesion, three views.\nexample = pd.DataFrame({\n    \"lesion_id\": [\"L1\", \"L1\", \"L1\"],\n    \"prob_mel\":  [0.20, 0.55, 0.30],\n    \"prob_nv\":   [0.80, 0.45, 0.70],\n})\nexample\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>lesion_id</th>\n      <th>prob_mel</th>\n      <th>prob_nv</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>L1</td>\n      <td>0.20</td>\n      <td>0.80</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>L1</td>\n      <td>0.55</td>\n      <td>0.45</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>L1</td>\n      <td>0.30</td>\n      <td>0.70</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#tbl-aggregation .cell tbl-cap='Per-image probabilities and the lesion-level values that replace them.' execution_count=13}\n``` {.python .cell-code}\nfrom ham10000.models import aggregate_probabilities, predicted_label\n\n# Combine probabilities first, then take one argmax.\ncombined = aggregate_probabilities(example, {\"max\": [\"mel\"], \"min\": [\"nv\"]})\n\ncomparison = example[[\"prob_mel\", \"prob_nv\"]].copy()\ncomparison.columns = [\"mel (per image)\", \"nv (per image)\"]\ncomparison[\"per-image verdict\"] = predicted_label(example)\ncomparison[\"mel (lesion)\"] = combined[\"prob_mel\"]\ncomparison[\"nv (lesion)\"] = combined[\"prob_nv\"]\ncomparison\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>mel (per image)</th>\n      <th>nv (per image)</th>\n      <th>per-image verdict</th>\n      <th>mel (lesion)</th>\n      <th>nv (lesion)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0.20</td>\n      <td>0.80</td>\n      <td>nv</td>\n      <td>0.55</td>\n      <td>0.45</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>0.55</td>\n      <td>0.45</td>\n      <td>mel</td>\n      <td>0.55</td>\n      <td>0.45</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>0.30</td>\n      <td>0.70</td>\n      <td>nv</td>\n      <td>0.55</td>\n      <td>0.45</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nChoosing `max` for melanoma (@tbl-aggregation) says: if any view of this lesion looked malignant, treat the lesion as that likely to be malignant. That is an explicitly sensitivity-favouring rule, appropriate to screening. The lesion columns are constant by construction, since the whole point is to replace each image's estimate with one figure for the lesion.\n\nThe alternative is to let each image vote and combine the labels.\n\n::: {#31 .cell execution_count=14}\n``` {.python .cell-code}\nfrom ham10000.models import aggregate_predictions\n\nvoted = example.assign(pred=predicted_label(example))\naggregate_predictions(voted, seed=0)[[\"lesion_id\", \"pred\", \"pred_final\"]]\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>lesion_id</th>\n      <th>pred</th>\n      <th>pred_final</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>L1</td>\n      <td>nv</td>\n      <td>nv</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>L1</td>\n      <td>mel</td>\n      <td>nv</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>L1</td>\n      <td>nv</td>\n      <td>nv</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nTies are broken at random, with a seed. The alternative is to take the first value in sorted order, which for integer labels means the lowest, and since `other` and `nv` occupy low indices that would quietly resolve tied lesions toward the benign class: the wrong direction for this problem.\n\nBoth rules are defensible. Whether the choice matters is a separate question, and a measurable one. The rest of this section uses the predictions from a completed run rather than the toy example above.\n\n::: {#33 .cell execution_count=15}\n``` {.python .cell-code}\nrun = next(\n    p for p in sorted((settings.root / \"models\").iterdir())\n    if p.name.startswith(\"balanced-with-random-crop\") and not p.name.endswith(\"-smoke\")\n)\npredictions = pd.read_csv(run / \"predictions.csv\")\n\n\nviews_per_lesion = predictions.groupby(\"lesion_id\")[\"pred\"].nunique()\nprint(f\"lesions whose views disagreed: {(views_per_lesion > 1).sum():,} \"\n      f\"of {len(views_per_lesion):,} ({(views_per_lesion > 1).mean():.1%})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlesions whose views disagreed: 432 of 1,870 (23.1%)\n```\n:::\n:::\n\n\n::: {#34 .cell execution_count=16}\n``` {.python .cell-code}\n# The route the pipeline used: vote on per-image labels -> pred_final.\n# The alternative: combine probabilities first, then take one argmax.\nby_probability = aggregate_probabilities(predictions, {\"max\": [\"mel\"]})\nby_probability[\"alt\"] = predicted_label(by_probability, seven.codes)\n\nper_lesion = by_probability.drop_duplicates(\"lesion_id\")\ndiffer = per_lesion[\"alt\"] != per_lesion[\"pred_final\"]\nprint(f\"routes disagree on {differ.sum():,} of {len(per_lesion):,} lesions \"\n      f\"({differ.mean():.1%})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nroutes disagree on 175 of 1,870 lesions (9.4%)\n```\n:::\n:::\n\n\nViews disagreed on 432 of 1,870 lesions (23.1%), but most of those are settled the same way by both rules. On 175 lesions (9.4%, about one in eleven) the two routes reach different verdicts. For those, the choice of aggregation rule is the answer.\n\nThe 23.1% also explains why the score moves between evaluations. Those lesions sit near the decision boundary, and re-cropping shifts some of them across it.\n\n::: {#tbl-disagreement .cell tbl-cap='One validation lesion where the two aggregation routes differ.' execution_count=17}\n``` {.python .cell-code}\ndisagreeing = per_lesion[differ]\n\n# Prefer a case where combining probabilities lands on melanoma, since that is\n# the direction the `max` rule is chosen for.\nmelanoma = seven.mapping[\"mel\"]\npreferred = disagreeing[disagreeing[\"alt\"] == melanoma]\nchosen = (preferred if len(preferred) else disagreeing).iloc[0][\"lesion_id\"]\n\nviews = predictions[predictions[\"lesion_id\"] == chosen]\ntable = views[seven.probability_columns].round(3)\ntable[\"per-image verdict\"] = views[\"pred\"].map(seven.codes)\n\nprint(f\"lesion {chosen}, one of {len(disagreeing)} where the two routes differ\")\nprint(f\"true diagnosis        : {views['dx'].iloc[0]}\")\nprint(f\"vote on labels        : {seven.codes[views['pred_final'].iloc[0]]}\")\nprint(f\"combine probabilities : \"\n      f\"{seven.codes[disagreeing.set_index('lesion_id').loc[chosen, 'alt']]}\")\ntable\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlesion HAM_0002730, one of 175 where the two routes differ\ntrue diagnosis        : bkl\nvote on labels        : bcc\ncombine probabilities : mel\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=17}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>prob_akiec</th>\n      <th>prob_bcc</th>\n      <th>prob_bkl</th>\n      <th>prob_df</th>\n      <th>prob_mel</th>\n      <th>prob_nv</th>\n      <th>prob_vasc</th>\n      <th>per-image verdict</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0.009</td>\n      <td>0.001</td>\n      <td>0.150</td>\n      <td>0.000</td>\n      <td>0.840</td>\n      <td>0.000</td>\n      <td>0.000</td>\n      <td>mel</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>0.071</td>\n      <td>0.537</td>\n      <td>0.185</td>\n      <td>0.008</td>\n      <td>0.189</td>\n      <td>0.004</td>\n      <td>0.006</td>\n      <td>bcc</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>0.012</td>\n      <td>0.242</td>\n      <td>0.690</td>\n      <td>0.004</td>\n      <td>0.047</td>\n      <td>0.002</td>\n      <td>0.003</td>\n      <td>bkl</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nLesion `HAM_0002730` is a benign keratosis. One view read it as melanoma at 0.84, another as basal cell carcinoma at 0.54, the third as keratosis at 0.69. Voting gives `bcc`; combining probabilities with `max` on melanoma gives `mel`.\n\nBoth are wrong, which makes this a more useful example than one where the sensitivity-favouring rule is vindicated. It shows the cost of the choice rather than only the benefit: `max` turns a single confident view into a melanoma call, and here that view was mistaken. In screening terms this is a false alarm and a biopsy, which is the price paid for catching the cases where the one suspicious view is right.\n\nThis also lets us check whether the expansion in section 5 earns its place. Over ten evaluations at each setting, three views scored 0.694 against 0.686 for one view, and the run-to-run spread fell from 0.018 to 0.014. The 23.1% figure above is why that spread exists at all: those lesions sit near the boundary, and re-cropping moves some of them across it. Neither difference is significant at this sample size, so the technique is retained because it is standard and costs little, not because this dataset shows it earning its keep.\n\n## 10. The decision rule\n\nPlain `argmax` is wrong for melanoma screening. A lesion at 45% melanoma against 50% nevus is called a nevus, and the two errors are not symmetric: a missed melanoma delays treatment of a cancer with a sharp survival gradient in time to diagnosis, while a false alarm costs a biopsy.\n\nTwo rules are available. They are different rules, not two implementations of one, and they disagree on roughly one lesion in six.\n\n::: {#tbl-rules .cell tbl-cap='Three decision rules on the same three probability vectors.' execution_count=18}\n``` {.python .cell-code}\nfrom ham10000.models import apply_cost_sensitive_weights, apply_priority_thresholds\n\ncases = pd.DataFrame({\n    \"prob_mel\": [0.45, 0.35, 0.42],\n    \"prob_bcc\": [0.05, 0.00, 0.45],\n    \"prob_nv\":  [0.50, 0.65, 0.13],\n})\n\nrules = [(\"plain argmax\", cases)]\nrules.append((\"priority (A)\",\n              apply_priority_thresholds(cases, promote=[(\"mel\", 0.4), (\"bcc\", 0.4)])))\nrules.append((\"cost-sensitive (C)\",\n              apply_cost_sensitive_weights(cases, thresholds=[(\"mel\", 0.4), (\"bcc\", 0.4)])))\npd.DataFrame({name: predicted_label(frame) for name, frame in rules})\n```\n\n::: {.cell-output .cell-output-display execution_count=18}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>plain argmax</th>\n      <th>priority (A)</th>\n      <th>cost-sensitive (C)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>nv</td>\n      <td>mel</td>\n      <td>mel</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>nv</td>\n      <td>nv</td>\n      <td>mel</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>bcc</td>\n      <td>mel</td>\n      <td>bcc</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n**Rule A, priority-ordered** (@tbl-rules), walks the list and promotes the *first* class clearing its bar, then stops. The ordering carries the clinical priority: melanoma is checked before basal cell carcinoma because it matters more. It is a gate: below the bar it does nothing at all, which is why row 2 stays `nv`. The rule is unorthodox: most work applies per-class thresholds independently or reweights, rather than walking an ordered list and stopping. However, the ordering makes the clinical priority explicit in a way a set of weights does not.\n\n**Rule C, cost-sensitive**, divides each probability by its threshold and takes the argmax. It is an unconditional reweighting, so it acts even when nothing crosses a bar, and row 2 flips to `mel`. Its effective condition is `p_mel > 0.4 · p_nv` rather than `p_mel > 0.4` (much weaker).\n\nRule A is the default. It is easy to reason about, and its priority ordering is an explicit statement of which class matters most, which suits a screening problem. Rule C is the more standard method and is available as an alternative; switching would change every reported figure, so the two are kept separate rather than swapped.\n\nRow 3 shows why a third variant is unattractive. If _both_ classes over 0.4 were promoted to 1.0, the tie would fall to column order, which is alphabetical, so `bcc` would beat `mel` because \"b\" precedes \"m\". That puts an arbitrary rule where a clinical one belongs, and it is the reason Rule A stops at the first class rather than promoting all of them.\n\n## 11. Evaluation\n\nPer lesion, not per image, so a lesion photographed five times counts once.\n\n::: {#43 .cell execution_count=19}\n``` {.python .cell-code}\nimport numpy as np\n\nfrom ham10000.evaluation import evaluate\nfrom ham10000.reporting import confusion_with_recall\n\ntarget = np.array([0, 0, 0, 0, 1, 1])\nprediction = np.array([0, 0, 0, 1, 0, 1])\ncodes = {0: \"nv\", 1: \"mel\"}\n\nreport = evaluate(target, prediction)\nprint(f\"plain accuracy    {report.accuracy:.3f}\")\nprint(f\"balanced accuracy {report.balanced_accuracy:.3f}\")\nprint(f\"F2               {report.f2:.3f}\")\nprint()\nprint(confusion_with_recall(target, prediction, codes).to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nplain accuracy    0.667\nbalanced accuracy 0.625\nF2               0.625\n\npred  nv  mel  support  recall\ntrue                          \nnv     3    1        4    0.75\nmel    1    1        2    0.50\n```\n:::\n:::\n\n\n**Balanced accuracy**, the mean of per-class recall, is the headline, because plain accuracy rewards predicting the majority class. Its chance level is `1/n_classes`, so scores from tasks with different class counts are not directly comparable.\n\n**F2** weights recall four times as heavily as precision, which is the direction a screening tool should err in. `F1/2` is reported alongside for contrast, not because it is appropriate here.\n\n**Support** sits beside recall because a recall of 1.00 over 18 lesions is not evidence of much.\n\n",
    "supporting": [
      "01_pipeline_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}